# Generated by Django 5.1.15 on 2026-03-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Número da Mesa')),
                ('capacity', models.IntegerField(default=4, verbose_name='Capacidade Total')),
                ('current_customers', models.IntegerField(default=0, verbose_name='Clientes na Mesa')),
                ('status', models.CharField(choices=[('available', 'Livre'), ('occupied', 'Ocupada'), ('bill', 'Pediu a Conta'), ('reserved', 'Reservada'), ('joined', 'Mesa Unida')], default='available', max_length=20)),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_tables', to='tables.table', verbose_name='Unida à Mesa')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
    ]
