# Generated by Django 5.1.15 on 2026-04-04 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='current_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='linked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_tables', to='tables.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
