# Generated by Django 5.1.15 on 2026-05-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_alter_ingredient_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (Compra/Ajuste)'), ('OUT', 'Saída (Perda/Desperdício)')], max_length=3, verbose_name='Tipo de Movimentação')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Justificativa')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-date'],
            },
        ),
    ]
